version: '2'

services:
    db:
      build: './sql_db'
      restart: always
      ports:
        - "3307:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
      networks: 
        - host
    ms:
      build: '.'
      ports:
        - "3010:3010"
      links:
        - db
      depends_on:
        - db
      networks: 
        - host
networks:
   host:
      driver: "bridge"
