version: '2'

services:
    db:
      build: './sql_db'
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
      networks: 
        - host
    ms:
      build: '.'
      ports:
        - "8086:8086"
      links:
        - db
      depends_on:
        - db
      networks: 
        - host
networks:
   host:
      driver: "bridge"
